import { ModeToggle } from "@/components/mode-toggle";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout for the app — wraps page content with global fonts, theme provider, and UI utilities.
 *
 * Renders the HTML skeleton and a body that applies Geist Sans and Geist Mono font variables and antialiasing.
 * Wraps children with a ThemeProvider configured to use the system theme by default (CSS class-based theming,
 * system detection enabled, and transitions disabled during theme changes). Also mounts a fixed ModeToggle and a
 * global Toaster positioned at the top-center.
 *
 * @param children - Page content to render inside the layout.
 * @returns The root JSX element for the application's layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed">
            <ModeToggle />
          </div>
          {children}
          <Toaster position="top-center" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
